name: Actualizar número de repositorios

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Obtener número de repos públicos
        run: |
          COUNT=$(curl -s https://api.github.com/users/tatiana1104 | grep '"public_repos"' | cut -d ':' -f2 | tr -d ', ')
          echo "Repos públicos: $COUNT"

          awk -v count="$COUNT" '
          /<!--REPO_COUNT-->/ {
            print "📦 Repositorios públicos: " count
            next
          }
          { print }
          ' README.md > README.tmp

          mv README.tmp README.md

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "🔄 Actualizar número de repositorios" || exit 0
          git push
