name: Actualizar repositorios

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Obtener número de repos públicos
        run: |
          COUNT=$(curl -s https://api.github.com/users/tatiana1104 | grep '"public_repos"' | sed 's/[^0-9]*//g')
          echo "Repos: $COUNT"

          sed -i "s/📦 Repositorios públicos:.*/📦 Repositorios públicos: $COUNT/" README.md

      - name: Commit cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Actualizar número de repositorios" || exit 0
          git push
